baseURL = "https://bulimov.me/"
languageCode = "en-us"
title = "Alexander Bulimov: Production Engineer and Scale Modeller"
theme = "xmin"
ignoreFiles = ["^public$"]

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Blog"
url = ""
weight = 1

[[menu.main]]
name = "Scale Models"
url = "https://models.bulimov.me"
weight = 2

[[menu.main]]
name = "Etc"
url = "etc/"
weight = 3

[[menu.main]]
name = "About Me"
url = "about/"
weight = 4

[params]
footer = "[![License: CC BY-SA 4.0](https://i.creativecommons.org/l/by-sa/4.0/80x15.png)](https://creativecommons.org/licenses/by-sa/4.0/) &copy; [Alexander Bulimov](http://bulimov.me) 2013 -- 2025 | [Github](https://github.com/abulimov)"

[markup.goldmark.renderer]
unsafe = true
